namespace: dev

apigateway:
  image: public.ecr.aws/y6x2k4a9/spring-petclinic-api-gateway #iguetoulene/spring-petclinic-api-gateway
  version: latest
  replicaCount: 2

customersservice:
  image: public.ecr.aws/y6x2k4a9/spring-petclinic-customers-service #iguetoulene/spring-petclinic-customers-service
  version: latest
  replicaCount: 1
  database:
    host: customer-db.czoc8a8mks78.us-east-1.rds.amazonaws.com:3306
    name: customerdb
    username: petcliniccustomer
    password: redacted

vetsservice:
  image: public.ecr.aws/y6x2k4a9/spring-petclinic-vets-service #iguetoulene/spring-petclinic-vets-service
  version: latest
  replicaCount: 1
  database:
    host: vet-db.czoc8a8mks78.us-east-1.rds.amazonaws.com:3306
    name: vetdb
    username: petclinicvet
    password: redacted

visitsservice:
  image: public.ecr.aws/y6x2k4a9/spring-petclinic-visits-service #iguetoulene/spring-petclinic-visits-service
  version: latest
  replicaCount: 1
  database:
    host: visit-db.czoc8a8mks78.us-east-1.rds.amazonaws.com:3306
    name: visitdb
    username: petclinicvisit
    password: redacted