namespace: staging
apigateway:
  replicaCount: 2
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-api-gateway
  version: 10304432389-113
customersservice:
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-customers-service
  version: 10384406803-105
  replicaCount: 1
vetsservice:
  replicaCount: 1
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-vets-service
  version: 10384303987-83
visitsservice:
  replicaCount: 1
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-visits-service
  version: 10385101656-47
database:
  host: petclinic-db.c5mqwqo0utao.us-east-1.rds.amazonaws.com:3306
  name: petclinicdb
  username: petclinicdbuser2024
  password: redacted
jdbcUrl: jdbc:mysql://petclinic-db.c5mqwqo0utao.us-east-1.rds.amazonaws.com:3306/petclinicdb
#?user=petclinicdbuser2024==&password=redacted
