spring:
  datasource:
    url: jdbc:mysql://vet-db.czoc8a8mks78.us-east-1.rds.amazonaws.com:3306/vetdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  