management.endpoints.web.exposure.include=restart,health,info
management.endpoint.restart.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.metrics.export.wavefront.WavefrontMetricsExportAutoConfiguration
management.metrics.export.wavefront.enabled=false
management.wavefront.enabled=false
management.wavefront.api-token=""
spring.cloud.config.enabled=false
logging.level.org.springframework.cloud.context.scope.GenericScope=OFF
logging.level.root=DEBUG