apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-reader
  namespace: production #{{ .Values.namespace }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-reader-binding
  namespace: production #{{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: production #{{ .Values.namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""         