apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  dbcustomerusername: "admin"
  dbcustomerpassword: {{ .Values.customersservice.database.password }}
  dbvetusername: "admin"
  dbvetpassword: {{ .Values.vetsservice.database.password }}
  dbvisitusername: "admin"
  dbvisitpassword: {{ .Values.visitsservice.database.password }}
  