apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  dbcustomerpassword: {{ .Values.databasecustomers.password }}
  dbvetpassword: {{ .Values.databasevets.password }}
  dbvisitpassword: {{ .Values.databasevisits.password }}