apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  dbcustomerpassword: "cGV0Y2xpbmljMjAyNGN1c3RvbWVy"
  dbvetpassword: "cGV0Y2xpbmljMjAyNHZldA=="
  dbvisitpassword: "cGV0Y2xpbmljMjAyNHZpc2l0"