apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  dbcustomerpassword: {{ .Values.customersservice.database.password | default "" | b64enc }}
  dbvetpassword: {{ .Values.vetsservice.database.password | default "" | b64enc }}
  dbvisitpassword: {{ .Values.visitsservice.database.password | default "" | b64enc }}