# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']

 # Job de scraping pour les noeuds Kubernetes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node

  # Job de scraping pour les pods Kubernetes
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter.monitoring.svc.cluster.local:9100']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
  # Job pour la collecte des métriques des services Spring Petclinic via Actuator
  - job_name: 'spring-petclinic-services'
    metrics_path: /actuator/prometheus
    kubernetes_sd_configs:
      - role: endpoints

  # Configuration de scraping des métriques HTTP pour les services spécifiques Petclinic

- job_name: api-gateway
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['api-gateway:8080']

- job_name: customers-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['customers-service:8081']

- job_name: visits-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['visits-service:8082']

- job_name: vets-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['vets-service:8083']
