# config file version
#apiVersion: 1

# list of datasources to insert/update depending what's available in the database
#datasources:
#- name: Prometheus
  #type: prometheus
  #access: proxy
  #org_id: 1
  #url: http://prometheus-server:9090
  #is_default: true
  #version: 1
  #editable: true
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus-server:9090
  is_default: true

dashboards:
- provider:
    name: 'default'
    orgId: 1
    folder: 'Petclinic'
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /var/lib/grafana/dashboards
