apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: "production" #{{ .Values.namespace }}
  annotations:
    #kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]' #'[{"HTTP": 80}, {"HTTPS":443}]'
    #alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:590184139086:certificate/5f92d975-9aac-4a98-a05e-2e56ed5fb532" #{{ .Values.apigateway.ingress.certificateArn }}
    #alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/subnets:  '["subnet-04418d92fe9eb385c","subnet-03fe8f2b2edf66247"]' #{{ .Values.apigateway.ingress.subnets }}
    alb.ingress.kubernetes.io/tags: "Name=alb-petclinic" #{{ .Values.apigateway.alb.tags }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: api-gateway-service
              port:
                number: 80
# enlever les commentaires pour le code une fois le certificat acm validé
#spec:
  #ingressClassName: alb
  #rules:
  #- host: "petclinicapp.net" #{{ .Values.apigateway.ingress.host }}
    #http:
      #paths:
      #- path: /
        #pathType: Prefix
        #backend:
          #service:
            #name: ssl-redirect
            #port:
              #name: use-annotation
      #- path: /
        #pathType: Prefix
        #backend:
          #service:
            #name: api-gateway
            #port:
              #number: 80