apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    #alb.ingress.kubernetes.io/certificate-arn: {{ .Values.apigateway.ingress.certificateArn }}
    #alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.apigateway.subnets }}
    #alb.ingress.kubernetes.io/tags: {{ .Values.alb.tags }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: api-gateway-service
              port:
                number: 80
# enlever les commentaires pour le code une fois le certificat acm validé
#spec:
  #rules:
  #- host: {{ .Values.ingress.host }}
    #http:
      #paths:
      #- path: /
        #pathType: Prefix
        #backend:
          #service:
            #name: ssl-redirect
            #port:
              #name: use-annotation
      #- path: /
        #pathType: Prefix
        #backend:
          #service:
            #name: api-gateway
            #port:
              #number: 80