apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: {{ .Values.apigateway.image }}:{{ .Values.apigateway.version }}
        name: api-gateway
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30  # Augmenté pour s'assurer que l'application est prête
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes,test
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config/application-primary.yaml
          subPath: application-primary.yaml
        - name: config-volume
          mountPath: /config/application-secondary.yaml
          subPath: application-secondary.yaml
        - name: config-volume
          mountPath: /config/application-tertiary.yaml
          subPath: application-tertiary.yaml
      volumes:
      - name: config-volume
        configMap:
          name: petclinic-config
          items:
          - key: application-primary.yaml
            path: application-primary.yaml
          - key: application-secondary.yaml
            path: application-secondary.yaml
          - key: application-tertiary.yaml
            path: application-tertiary.yaml