apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: {{ .Values.apigateway.image }}:{{ .Values.apigateway.version }}
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: {{- if .Values.customersservice -}}:
                      dbcustomerusername
                    {{- else if .Values.vetsservice -}}:
                      dbvetusername
                    {{- else if .Values.visitsservice -}}:
                      dbvisitusername
                    {{- end }}
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: {{- if .Values.customersservice -}}:
                      dbcustomerpassword
                    {{- else if .Values.vetsservice -}}:
                      dbvetpassword
                    {{- else if .Values.visitsservice -}}:
                      dbvisitpassword
                    {{- end }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes,test
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: config-volume
          subPath: application-primary.yaml
          mountPath: /config/application-primary.yaml
        - name: config-volume
          subPath: application-secondary.yaml
          mountPath: /config/application-secondary.yaml
        - name: config-volume
          subPath: application-tertiary.yaml
          mountPath: /config/application-tertiary.yaml
      volumes:
      - name: config-volume
        configMap:
          name: petclinic-config