apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.customersservice.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: customers-service
  strategy: {}
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      serviceAccountName: rds-access-sa
      containers:
      - image: {{ .Values.customersservice.image }}:{{ .Values.customersservice.version }}
        name: customers-service
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            cpu: 500m
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value:  kubernetes
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.customersservice.database.username }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: dbpassword
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://{{ .Values.customersservice.database.dbname }}.{{ .Values.customersservice.database.dbhost }}/{{ .Values.customersservice.database.dbname }}?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db
        ports:
        - containerPort: 8080
      restartPolicy: Always