apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.customersservice.replicaCount }}
  selector:
    matchLabels:
      app: customers-service
  strategy: {}
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
      - image: {{ .Values.customersservice.image }}:{{ .Values.customersservice.version }}
        name: customers-service
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.customersservice.database.username }}
        - name: DATABASE_URL
          value: {{ .Values.customersservice.database.jdbcUrl }}
        #- name: SPRING_DATASOURCE_PASSWORD
          #valueFrom:
             #secretKeyRef:
               #name: database-secret
               #key: dbcustomerpassword
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
