apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vets-service
  name: vets-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.vetsservice.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: vets-service
  strategy: {}
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      serviceAccountName: rds-access-sa
      containers:
      - image: {{ .Values.vetsservice.image }}:{{ .Values.vetsservice.version }}
        name: vets-service
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value:  kubernetes,test
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.database.username }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: dbpassword
        - name: SPRING_DATASOURCE_URL
          value: {{ .Values.jdbcUrl }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
      restartPolicy: Always
