apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: visits-service
  name: visits-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.visitsservice.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: visits-service
  strategy: {}
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - image: {{ .Values.visitsservice.image }}:{{ .Values.visitsservice.version }}
        name: visits-service
        imagePullPolicy: Always
        #livenessProbe:
          #httpGet:
            #port: 8080
            #path: /actuator/health/liveness
          #initialDelaySeconds: 90
          #periodSeconds: 5
        #readinessProbe:
          #httpGet:
            #port: 8080
            #path: /actuator/health/readiness
          #initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            cpu: 500m
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value:  kubernetes
        - name: SPRING_DATASOURCE_USERNAME
          value: {{.Values.visitsservice.database.username }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: dbpassword
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://{{ .Values.visitsservice.database.dbhost }}/{{ .Values.visitsservice.database.dbname }}?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=visits-db
        ports:
        - containerPort: 8080
      restartPolicy: Always